### ISSUE TITLE
'toggled' prop has no effect in CDBSidebar

### ISSUE THREAD

**Issue by remleduff** [Devwares-Team/cdbreact#10]
From what I can tell, there's no way to set CDBSidebar to start expanded. It's always collapsed, despite the value of the toggled property.

**Comment by remleduff** [comment]
Reproduced by cloning: https://github.com/Chimdiya1/article-sidebar.git and upgrading to cdbreact 1.5.1

**Comment by Speedwares** [comment]
Hey @remleduff thanks for reporting this and submitting a pull request to fix this. I will try to reproduce this in a few and merge the fix if everything checks out.
