### ISSUE TITLE
Next button doesn't work and doesn't show pages

### ISSUE THREAD

**Issue by m3nur** [Devwares-Team/cdbreact#15]

**Comment by m3nur** [comment]
DataTable

**Comment by m3nur** [comment]
I found the answer! Pagination does not work in version **1.5.7** to solve this problem, you need to install **1.5.3**

**Comment by Speedwares** [comment]
@NurMura88 can you confirm if this has been fixed on version 1.5.8?

**Comment by m3nur** [comment]
@Speedwares  Yes, now everything works, but there is one problem, if there are more than 4 pages, then the **NEXT** button goes beyond the block)

**Comment by Speedwares** [comment]
I see. Can you create that as a separate issue?
Would be very helpful too if you can attach a screenshot!
