### ISSUE TITLE
I get this error  => "Uncaught TypeError: Cannot convert undefined or null to object" 

### ISSUE THREAD

**Issue by m3nur** [Devwares-Team/cdbreact#21]
![Desktop screenshot (1)](https://user-images.githubusercontent.com/45517204/226102574-e50c47bb-ffad-4c6f-a7d2-e64c1e2f73bb.png)

**Comment by m3nur** [comment]
There is no such error in earlier versions, please fix it

**Comment by MaximeNe** [comment]
Same problem here,
It looks like it apears with high value of entriesOptions in datatable for me

**Comment by Speedwares** [comment]
@m3nur @MaximeNe thanks for reporting this. We will take look ASAP

**Comment by Speedwares** [comment]
@m3nur @MaximeNe can you replicate this on [codesandbox](https://codesandbox.io/) ? I have not been able to replicate this with the data table component

**Comment by MaximeNe** [comment]
https://codesandbox.io/p/sandbox/naughty-sara-3qws3i?welcome=true
I have some buttons to set the data in the DataTable. When paging is true and custom entresOptions is used, then clicking on the "5000" btn, then the "1000" btn and then the "5000" btn make the app crash.
If the combination does not work, try other combinations of butons.

**Comment by Speedwares** [comment]
@MaximeNe Thanks for the codesandbox! This issue was fixed in the latest version of cdbreact!

It should be fixed once you update to the latest version v1.5.13 . But let me if you are still getting this error after updating 
CC: @m3nur

**Comment by m3nur** [comment]
I will let you know when I check, thank you very much.

**Comment by MaximeNe** [comment]
This seems to work properly for me now thanks !
