### ISSUE TITLE
Stepper component spacing when hiding title

### ISSUE THREAD

**Issue by buildxyz-git** [Devwares-Team/cdbreact#26]
When I set the `showTitle` prop on `CDBStepper` to false, there is uneven spacing:
```
<CDBStepper
    direction="vertical"
    stepSize={45}
    showTitle={false}
    showTooltip={true}
...
```

![Screenshot 2023-04-11 at 2 24 56 PM](https://user-images.githubusercontent.com/16586332/231291718-708b7839-577b-48cc-9b28-4187c918a7ff.png)

Additionally, is there any chance we can separate `showTitle` and add a new prop `showIndex` for those who want to keep the step number but drop the title? I think this may be valuable when viewing on Mobile.

**Comment by Speedwares** [comment]
@buildxyz-git This issue has been resolved in the latest update for cdbreact pro and in the new version of cdbreact. You should have received an email to download the new version of the pro library.

The documentation has been updated as well [stepper doc](https://www.devwares.com/docs/contrast/react/components/stepper/ ). Let me know if this was resolved on your end after the update
