### ISSUE TITLE
Responsive Sidebar?

### ISSUE THREAD

**Issue by shg1998** [Devwares-Team/cdbreact#3]
Hi, Thanks for this great Project.
The Sidebar Default Width is 270px, is any attribute in CDBSidebar for setting manual width?

if not, I suggest a way:
Replace 270 with 100%!
thanks for help

**Comment by Speedwares** [comment]
Hello @shg1998,

Thanks for your kind words. About the sidebar width you are correct it currently has a  default width of 270px.

But I don't think setting a width of 100% would get you exactly what you want. We can create a prop in the sidebar component that can be used to change the width to whatever value you need it to be. We will definitely be adding this to the next version release coming soon. 

But feel free to make a pull request with this feature and we will be happy to go through and merge if it passes all our checks.

**Comment by shg1998** [comment]
Thanks a lot 
about this sentence "But I don't think setting a width of 100% would get you exactly what you want"
I tested it and got the desired result. because I set the width by its parent Container using Bootstrap Grid (Col-...)
I look forward to the next release👌
Thanks for your reply

**Comment by Speedwares** [comment]
Awesome!!! Glad that sorted it out for you. 
Thanks for bringing this to our notice.
