### ISSUE TITLE
bootstrap-css-only dependency causes theming issues with rest of application

### ISSUE THREAD

**Issue by buildxyz-git** [Devwares-Team/cdbreact#31]
I was trying to troubleshoot an issue where I could not overwrite Bootstrap's `$theme-color` map and it turned out by removing cdbreact from my project the issue was resolved. This is likely due to variable redefinition in cdbreact dependancy:
```
"bootstrap-css-only": "^4.4.1",
```
Curious if others have had this issue or if there is some misconcfiguration with my project.

**Comment by Speedwares** [comment]
Hey @buildxyz-git

Could you replicate this on Codesandbox so I can take a closer look? However, `"bootstrap-css-only"` is no longer a dependency, as we have moved on from it.

I will update this in the next release.
