### ISSUE TITLE
I attempetd to use the example with a cta but i go this error instead

### ISSUE THREAD

**Issue by tonyrex99** [Devwares-Team/cdbreact#32]
Attempted import error: 'CDBSidebarCTA' is not exported from 'cdbreact' (imported as 'CDBSidebarCTA').
ERROR in ./src/pages/MainOverview.js 80:35-48
export 'CDBSidebarCTA' (imported as 'CDBSidebarCTA') was not found in 'cdbreact' (possible exports: CDBAccordion, CDBAlert, CDBAnimation, CDBBadge, CDBBox, CDBBreadcrumb, CDBBtn, CDBBtnGrp, CDBBtnTb, CDBCard, CDBCardBody, CDBCarousel, CDBCarouselInner, CDBCarouselItem, CDBCloseIcon, CDBCol, CDBCollapse, CDBContainer, CDBDataTable, CDBDropDown, CDBDropDownItem, CDBDropDownMenu, CDBDropDownToggle, CDBHamburgerToggler, CDBIcon, CDBIframe, CDBInput, CDBInputGroup, CDBJumbotron, CDBLink, CDBListGroup, CDBListGroupItem, CDBMask, CDBModal, CDBModalBody, CDBModalFooter, CDBModalHeader, CDBNavBrand, CDBNavItem, CDBNavLink, CDBNavToggle, CDBNavbar, CDBNavbarNav, CDBPageItem, CDBPageLink, CDBPagination, CDBProgress, CDBRating, CDBRow, CDBSelect, CDBSidebar, CDBSidebarContent, CDBSidebarFooter, CDBSidebarHeader, CDBSidebarMenu, CDBSidebarMenuItem, CDBSlider, CDBSmoothScroll, CDBSpinner, CDBStep, CDBStepper, CDBSwitch, CDBTable, CDBTableBody, CDBTableHeader, CDBView)

webpack compiled with 1 error

i used npm toinstall cdbreact and i also checked for upgrades to no results

/////my code/////
import React, { useCallback, useState } from "react";
import {
  CDBSidebar,
  CDBSidebarHeader,
  CDBSidebarMenuItem,
  CDBSidebarContent,
  CDBSidebarMenu,
  CDBSidebarSubMenu,
  CDBSidebarFooter,
  CDBBadge,
  CDBContainer,
  CDBSidebarCTA,
} from "cdbreact";

const Sidebar = () => {
  return (
    <CDBSidebar textColor="#fff" backgroundColor="#333">
      <CDBSidebarHeader prefix={<i className="fa fa-bars" />}>
        With CTA
      </CDBSidebarHeader>
      <CDBSidebarContent>
        <CDBSidebarMenu>
          <CDBSidebarMenuItem icon="th-large" iconSize="lg">
            Dashboard
          </CDBSidebarMenuItem>
          <CDBSidebarMenuItem icon="sticky-note" iconSize="sm">
            Components
          </CDBSidebarMenuItem>
          <CDBSidebarMenuItem
            icon="credit-card"
            iconType="solid"
            textFontSize="14px"
          >
            Sales
          </CDBSidebarMenuItem>
          <CDBSidebarMenuItem
            icon="gamepad"
            iconType="solid"
            textFontSize="14px"
          >
            Games
          </CDBSidebarMenuItem>
        </CDBSidebarMenu>
      </CDBSidebarContent>
      <CDBSidebarCTA
        theme="overlay"
        text="This sidebar contains a CTA component. You can add anything you want here; text, images or a custom component"
      ></CDBSidebarCTA>
      <CDBSidebarFooter style={{ textAlign: "center" }}>
        <div className="sidebar-btn-wrapper" style={{ padding: "20px 5px" }}>
          Sidebar Footer
        </div>
      </CDBSidebarFooter>
    </CDBSidebar>
  );
};

**Comment by Speedwares** [comment]
The CTA component is only available in the premium version of cdbreact, which is cdbreact pro. 
Here is a link if you want to check it out https://www.devwares.com/product/contrast-pro/
