### ISSUE TITLE
there is no CDBSidebarSubMenu v1.5.17?

### ISSUE THREAD

**Issue by Denmark2** [Devwares-Team/cdbreact#39]
hi ill try to install the lastest version but i have a problem with CDBSidebarSubMenu is missing.

**Comment by Speedwares** [comment]
Hey,

CDBSidebarSubMenu is a premium component therefore it’s not available in
cdbreact, but rather in cdbreact-pro. Here is a link to learn more
https://www.devwares.com/product/contrast-pro
