### ISSUE TITLE
Performance Metering

### ISSUE THREAD

**Issue by L1lith** [Devwares-Team/cdbreact#7]
This one isn't immediately necessary, but when you get time it might be good to do some performance measurements. [Benchmark](https://www.npmjs.com/package/benchmark) is a really useful library for this but you can use whatever lib you want. Making performance optimizations is not a very practical thing to do before you have measurements in place. Thanks for listening to all my suggestions, and good luck with your library 😄

**Comment by Speedwares** [comment]
You are very welcome 🙂.  Just checked benchmark out, will try it out once I decide on what to measure, and would like to start optimizing for those. Thank you very much for all your helpful suggestions 🙏🙏
