### ISSUE TITLE
CDBIcon' is not exported from 'cdbreact

### ISSUE THREAD

**Issue by akshat-khosya** [Devwares-Team/cdbreact#8]
import React,{useState} from "react";
import { BrowserRouter as Router } from 'react-router-dom';
import { CDBNavbar, CDBNavBrand, CDBNavItem, CDBNavLink, CDBDropDown, CDBDropDownMenu, CDBDropDownToggle, CDBBtn, CDBNavToggle, CDBCollapse, CDBNavbarNav, CDBContainer } from "cdbreact";
import { CDBIcon } from "cdbreact";
const Navbar = () => {
  const [collapse2, setCollapse2] = useState(false);

  const bgBlack = { backgroundColor: "#000000", color: "#f4f4f4" };

  return (
    <CDBContainer>
        <Router style={{ width: "100%" }}>
              <CDBNavbar style={bgBlack} dark expand="md" scrolling>
                <CDBNavBrand href="/">
                  <strong>Navbar</strong>
                </CDBNavBrand>
                <CDBNavToggle
                  onClick={() => {
                    setCollapse2(!collapse2);
                  }}
                />
                <CDBCollapse id="navbarCollapse1" isOpen={collapse2} navbar>
                  <CDBNavbarNav left className="align-items-center">
                    <CDBNavItem>
                      <CDBDropDown>
                        <CDBDropDownToggle
                          caret
                          style={{ padding: 0 }}
                          color="dark"
                          circle
                        >
                          Categories
                        </CDBDropDownToggle>
                        <CDBDropDownMenu>
                          Coming soon #pleaseStayUpdated.
                        </CDBDropDownMenu>
                      </CDBDropDown>
                    </CDBNavItem>
                    <CDBNavItem>
                      <CDBBtn circle color="dark" style={{ padding: 0 }}>
                        <CDBNavLink to="#">Help</CDBNavLink>
                      </CDBBtn>
                    </CDBNavItem>
                    <CDBNavItem>
                      <CDBBtn circle color="dark" style={{ padding: 0 }}>
                        <CDBNavLink to="#">About</CDBNavLink>
                      </CDBBtn>
                    </CDBNavItem>
                  </CDBNavbarNav>
                  <CDBNavbarNav right>
                    <CDBNavItem>
                      <CDBBtn circle color="dark" style={{ padding: 0 }}>
                        <CDBNavLink to="#">
                          <CDBIcon className="mr-2" icon="globe" />
                          EN
                        </CDBNavLink>
                      </CDBBtn>
                    </CDBNavItem>

                    <CDBNavItem>
                      <CDBBtn circle color="dark" style={{ padding: 0 }}>
                        <CDBNavLink to="#">
                          <CDBIcon className="mr-2" icon="user" />
                          Login
                        </CDBNavLink>
                      </CDBBtn>
                    </CDBNavItem>
                    <CDBNavItem>
                      <CDBBtn color="white" style={{ padding:"0px 10px" }}>
                        <CDBNavLink to="#" style={{ color: "#000" }}>
                          Sign Up
                        </CDBNavLink>
                      </CDBBtn>
                    </CDBNavItem>
                  </CDBNavbarNav>
                </CDBCollapse>
              </CDBNavbar>
        </Router>
    </CDBContainer>
  );
};
export default  Navbar;

// I used this code but giving this error CDBIcon' is not exported from 'cdbreact

**Comment by Speedwares** [comment]
Hello akshat,

That is because CDBICON is a pro component. You can get the pro version of the library here https://www.devwares.com/product/contrast-pro or you can remove the CDBICON import, all its uses cases in your code and use another icon library instead. Hope this helps
