### ISSUE TITLE
Is it possible to upgrade the peerDependencies?

### ISSUE THREAD

**Issue by hayate** [Devwares-Team/cdbreact#9]
from:
```conf
"react": "^16.13.0",
"react-dom": "^16.13.0",
```
to:
```conf
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

**Comment by Speedwares** [comment]
Hey,

Thanks for letting us know about this. We just updated the peer dependencies to allow you to work with cdbreact on react 16 or react 17 in the new patch we just uploaded. Try running npm install again.

Let me know if this sorts out the warning you were getting on react 17.

Cheers

**Comment by hayate** [comment]
@Speedwares This is perfect thank you!
